help:
  @just --list

publish: upload

# Bump patch version and publish
republish: patch upload

patch:
  yarn version --patch

# Build and publish to npm
upload:
  npm publish --access=public
  rm -drf dist

# Compile the package into dist/
build:
  yarn run build
